// <auto-generated />
namespace Pzpn.Team.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fsd5_597F109319C8409BA2977F6DC1EFD0EB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fsd5_597F109319C8409BA2977F6DC1EFD0EB));
        
        string IMigrationMetadata.Id
        {
            get { return "201712021206065_Fsd5_597F109319C8409BA2977F6DC1EFD0EB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
