// <auto-generated />
namespace Pzpn.Team.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fsd5_888D9B3B508843B49B6A7624208E0B35 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fsd5_888D9B3B508843B49B6A7624208E0B35));
        
        string IMigrationMetadata.Id
        {
            get { return "201712021117209_Fsd5_888D9B3B508843B49B6A7624208E0B35"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
