// <auto-generated />
namespace Pzpn.Team.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fsd5_E53E33480C904F04AA2C843D3E818B6B : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fsd5_E53E33480C904F04AA2C843D3E818B6B));
        
        string IMigrationMetadata.Id
        {
            get { return "201712021119100_Fsd5_E53E33480C904F04AA2C843D3E818B6B"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
