// <auto-generated />
namespace Pzpn.Team.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fsd5_18FD946917584B3EA33FA0E954C80D05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fsd5_18FD946917584B3EA33FA0E954C80D05));
        
        string IMigrationMetadata.Id
        {
            get { return "201712021149414_Fsd5_18FD946917584B3EA33FA0E954C80D05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
