// <auto-generated />
namespace Pzpn.Team.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fsd5_362BA5C345FC4B979E57FC10E0499D6C : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fsd5_362BA5C345FC4B979E57FC10E0499D6C));
        
        string IMigrationMetadata.Id
        {
            get { return "201712021103589_Fsd5_362BA5C345FC4B979E57FC10E0499D6C"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
